title: Awesome FastAPI
email: your-email@example.com
description: >-
  A collection of third-party tools to power your next FastAPI project. Maintained by
  Mahmoud Harmouch.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fastapi.wiseai.dev" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-seo-tag
include:
  - README.md
exclude:
  - "*.md"
  - Gemfile*
  - justfile
  - LICENSE
  - Makefile
  - modd.conf
  - node_modules
  - package*.json
  - postcss.config.js
  - src
  - tailwind.config.js
  - vendor
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: "README.md"
    values:
      permalink: "/"
      layout: "default"

aux_links:
  "Awesome FastAPI on GitHub":
    - "//github.com/wiseaidev/awesome-fastapi"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

color_scheme: dark

heading_anchors: true

footer_content: >-
  ⚠️ Note: I live in Lebanon and e-wallets such as PayPal, Stripe, Skrill, and Coinbase are not
  compliant with Lebanese bank accounts. This means it is completely infeasible for me
  to set up GitHub Sponsors, OpenCollective, or services that rely on them. Sorry, 
  there is no way you can support me for now. For more info about the situation over
  here, you can refer to <a href="https://dev.to/wiseai/lebanon-the-devastating-life-59e3" target="_blank">this post</a>.

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/wiseaidev/awesome-fastapi" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately


search_enabled: false

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false


nav_external_links:
  - title: Third-Party Packages
    url: "#third-party-packages"
    hide_icon: true
  - title: Python Packages
    url: "#python-packages"
    hide_icon: true
  - title: Resources
    url: "#resources"
    hide_icon: true
  - title: Hosting
    url: "#hosting"
    hide_icon: true
  - title: Projects
    url: "#projects"
    hide_icon: true
  - title: FastAPI Framework
    url: "#fastapi-framework"
    hide_icon: true
